modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/NetherPortalFix/issues"

[[mods]]
modId="netherportalfix"
version="${mod_version}"
displayName="NetherPortalFix"
displayURL="https://mods.twelveiterations.com/mc/netherportalfix"
logoFile="netherportalfix-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
Ensures correct destinations when travelling back and forth through Nether Portals in Multiplayer.
'''

[[dependencies.netherportalfix]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherportalfix]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.netherportalfix]]
    modId="balm"
    mandatory=true
    versionRange="${balm_version_range}"
    ordering="NONE"
    side="BOTH"
